name: Bundle and Publish Sources
on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

jobs:
  build:
    name: Bundle and Publish Sources
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.1.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Checkout existing bundles
        uses: actions/checkout@v4.1.2
        continue-on-error: true
        with:
          ref: gh-pages
          path: bundles

      # Clean npm cache before installing dependencies
      - name: Clean npm cache
        run: npm cache clean --force

      # Install dependencies (including paperback-extensions-common)
      - name: Install dependencies
        run: npm install

      # Optional: Ensure paperback-extensions-common is installed
      - name: Install paperback-extensions-common (if necessary)
        run: npm install paperback-extensions-common

      # Run the bundle command with the extracted branch
      - run: npm run bundle -- --folder=${{ steps.extract_branch.outputs.branch }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: bundles

      # Optional: Check if paperback-extensions-common is installed (debug step)
      - name: Debug Installed Packages
        run: npm list paperback-extensions-common

